# Use @ Before The Command To Prevent Print The Command
# You Can Use Varibles Here
# Use $() To Put Your Variable Name


# Work With Python Files
file = hello
python:
	@python3 $(file).py
# Work With C Files
C: 
	@gcc file.c -o file.o
	@./file.o
# Work With Bash Commands
bash: 
	@rm file 
	@touch bash.txt
	@echo "Hello From Created Bash" > bash.txt
